name: Mike Georgia at Soundcloud
favicon: null
layout_spectrum: 0.4568870256189257
typography_spectrum: 0.6877384106628597
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#d39247'
    - '#9d3417'
    - '#7f6a3a'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
