name: Mike Georgia at Soundcloud
favicon: null
layout_spectrum: 0.4568870256189257
typography_spectrum: 0.6877384106628597
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9972496752161533
  lightness: 0.7246308873873204
  saturation: 0.34398873895406723
  rhythmicContrast: 0.7281503414269537
purpose: []
